# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/tf_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tf_window(object):
    def setupUi(self, tf_window):
        tf_window.setObjectName("tf_window")
        tf_window.resize(393, 285)
        self.OK_btn = QtWidgets.QDialogButtonBox(tf_window)
        self.OK_btn.setEnabled(True)
        self.OK_btn.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.OK_btn.setOrientation(QtCore.Qt.Horizontal)
        self.OK_btn.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.OK_btn.setObjectName("OK_btn")
        self.layoutWidget = QtWidgets.QWidget(tf_window)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 15, 371, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tf_title = QtWidgets.QLineEdit(self.layoutWidget)
        self.tf_title.setText("")
        self.tf_title.setObjectName("tf_title")
        self.gridLayout.addWidget(self.tf_title, 0, 0, 1, 1)
        self.tf_raw = QtWidgets.QLineEdit(self.layoutWidget)
        self.tf_raw.setEnabled(False)
        self.tf_raw.setObjectName("tf_raw")
        self.gridLayout.addWidget(self.tf_raw, 1, 0, 1, 1)
        self.expr_plot = ExprWidget(self.layoutWidget)
        self.expr_plot.setObjectName("expr_plot")
        self.gridLayout.addWidget(self.expr_plot, 2, 0, 1, 1)
        self.check_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.check_btn.setEnabled(True)
        self.check_btn.setObjectName("check_btn")
        self.gridLayout.addWidget(self.check_btn, 3, 0, 1, 1)
        self.error_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_label.sizePolicy().hasHeightForWidth())
        self.error_label.setSizePolicy(sizePolicy)
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.gridLayout.addWidget(self.error_label, 4, 0, 1, 1)

        self.retranslateUi(tf_window)
        self.OK_btn.accepted.connect(tf_window.accept)
        self.OK_btn.rejected.connect(tf_window.reject)
        QtCore.QMetaObject.connectSlotsByName(tf_window)

    def retranslateUi(self, tf_window):
        _translate = QtCore.QCoreApplication.translate
        tf_window.setWindowTitle(_translate("tf_window", "Transfer Function"))
        self.tf_title.setPlaceholderText(_translate("tf_window", "Title"))
        self.tf_raw.setPlaceholderText(_translate("tf_window", "Function"))
        self.check_btn.setText(_translate("tf_window", "Check Expression"))
from src.widgets.exprwidget import ExprWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tf_window = QtWidgets.QDialog()
    ui = Ui_tf_window()
    ui.setupUi(tf_window)
    tf_window.show()
    sys.exit(app.exec_())
